export const projectsData = [
  {
    id: 0,
    img: process.env.PUBLIC_URL + "/assets/dco.png",
    title: "Microsoft DCO",
    desc: "Developed Microsoft DCO site. For simplifying Azure cloud transformation.",
    techStack: "ASP.NET, Bootstrap 5",
    livePreview: "https://microsoftusdco.azurewebsites.net/",
  },
  {
    id: 1,
    img: process.env.PUBLIC_URL + "/assets/songify.png",
    title: "Songify",
    desc: "A responsive web application to explore and enjoy a collection of your favorite tunes.",
    techStack: "HTML 5, CSS 3, JavaScript",
    livePreview: "https://manhar-chaurasia.github.io/Songify/",
    repoLink: "https://github.com/Manhar-Chaurasia/Songify",
  },
  {
    id: 2,
    img: process.env.PUBLIC_URL + "/assets/pixabay.png",
    title: "Pixabay Lite",
    desc: "Developed Pixabay Lite: Responsive website using Tailwind CSS for an optimal user experience.",
    techStack: "Tailwind CSS",
    livePreview: "https://manhar-chaurasia.github.io/pixabay-lite/",
    repoLink: "https://github.com/Manhar-Chaurasia/pixabay-lite",
  },
  {
    id: 3,
    img: process.env.PUBLIC_URL + "/assets/crypto.png",
    title: "Live Cryptocurrency",
    desc: "Stay updated with real-time cryptocurrency prices using this dynamic web-based tracker.",
    techStack: "ReactJs",
    livePreview: "https://manhar-chaurasia.github.io/LiveCryptocurrency/",
    repoLink: "https://github.com/Manhar-Chaurasia/LiveCryptocurrency",
  },
  {
    id: 4,
    img: process.env.PUBLIC_URL + "/assets/fithub.png",
    title: "Fithub (Gym-Site)",
    desc: "A Redux Toolkit and React.js-powered gym site provides a streamlined user experience, showcasing various exercises and detailed instructions for effective fitness routines.",
    techStack: "ReactJs, Redux Toolkit",
    livePreview: "https://manhar-chaurasia.github.io/gym-site/",
    repoLink: "https://github.com/Manhar-Chaurasia/gym-site",
  },
  {
    id: 5,
    img: process.env.PUBLIC_URL + "/assets/courses.png",
    title: "Top Courses",
    desc: "Explore a curated list of top courses across various subjects to aid in your learning journey.",
    techStack: "ReactJs",
    livePreview: "https://manhar-chaurasia.github.io/Top-Courses/",
    repoLink: "https://github.com/Manhar-Chaurasia/Top-Courses",
  },
];
